# Generated by Django 3.0.7 on 2020-08-10 16:59

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disabled', models.BooleanField(default=False)),
                ('designation', models.CharField(choices=[('Admin', 'Admin'), ('Supervisor', 'Supervisor'), ('Analyst', 'Analyst')], default='Analyst', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=128, null=True)),
                ('targets', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), default=list, size=None)),
                ('description', models.CharField(max_length=512)),
                ('category', models.CharField(choices=[('Robbery', 'Robbery'), ('Theft', 'Theft'), ('Bomb Blast', 'Bomb Blast'), ('Other', 'Other')], default='Other', max_length=32)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Close', 'Close'), ('Delayed', 'Delayed')], default='Open', max_length=32)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('accounts', models.ManyToManyField(blank=True, related_name='accounts', to='api.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=128, null=True)),
                ('zone', models.CharField(default=None, max_length=128, null=True)),
                ('head', models.CharField(default=None, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(default=None, max_length=128, null=True)),
                ('serverJobId', models.CharField(default=None, max_length=128, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('FINISHED', 'FINISHED')], default='PENDING', max_length=32)),
                ('category', models.CharField(choices=[('IMSI', 'IMSI'), ('IMEI', 'IMEI'), ('MSISDN', 'MSISDN'), ('Location', 'Location'), ('LAC/Cell-ID', 'LAC/Cell-ID')], default='IMSI', max_length=32)),
                ('startTime', models.BigIntegerField(default=-1)),
                ('endTime', models.BigIntegerField(default=-1)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Case')),
            ],
        ),
        migrations.CreateModel(
            name='HandsetHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_type', models.CharField(choices=[('IMSI', 'IMSI'), ('IMEI', 'IMEI'), ('MSISDN', 'MSISDN')], default='IMSI', max_length=32)),
                ('msisdnorimei', models.CharField(max_length=32)),
                ('imsi', models.CharField(max_length=32)),
                ('startTime', models.BigIntegerField(default=-1)),
                ('endTime', models.BigIntegerField(default=-1)),
                ('job', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api.Job')),
            ],
        ),
        migrations.CreateModel(
            name='CallDetailRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geohash', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('yyyymm', models.BigIntegerField(default=-1, null=True)),
                ('timestamp', models.BigIntegerField(default=-1)),
                ('timebucket', models.CharField(default=None, max_length=128, null=True)),
                ('servedimsi', models.BigIntegerField(default=-1)),
                ('servedimei', models.BigIntegerField(default=-1)),
                ('servedmsisdn', models.BigIntegerField(default=-1)),
                ('callingnumber', models.BigIntegerField(default=-1)),
                ('callednumber', models.BigIntegerField(default=-1)),
                ('recordingentity', models.BigIntegerField(default=-1)),
                ('locationlat', models.FloatField(default=-1)),
                ('locationlon', models.FloatField(default=-1)),
                ('seizureordeliverytime', models.BigIntegerField(default=-1)),
                ('answertime', models.BigIntegerField(default=-1)),
                ('releasetime', models.BigIntegerField(default=-1)),
                ('callduration', models.BigIntegerField(default=-1)),
                ('causeforterm', models.BigIntegerField(default=-1)),
                ('diagnostics', models.BigIntegerField(default=-1)),
                ('callreference', models.CharField(default=None, max_length=128, null=True)),
                ('sequencenumber', models.BigIntegerField(default=-1)),
                ('networkcallreference', models.CharField(default=None, max_length=128, null=True)),
                ('mscaddress', models.BigIntegerField(default=-1)),
                ('systemtype', models.CharField(default=None, max_length=128, null=True)),
                ('chargedparty', models.CharField(default=None, max_length=128, null=True)),
                ('calledimsi', models.BigIntegerField(default=-1)),
                ('subscribercategory', models.CharField(default=None, max_length=128, null=True)),
                ('firstmccmnc', models.CharField(default=None, max_length=128, null=True)),
                ('intermediatemccmnc', models.CharField(default=None, max_length=128, null=True)),
                ('lastmccmnc', models.CharField(default=None, max_length=128, null=True)),
                ('usertype', models.CharField(default=None, max_length=128, null=True)),
                ('recordnumber', models.BigIntegerField(default=-1)),
                ('partyrelcause', models.CharField(default=None, max_length=128, null=True)),
                ('chargelevel', models.CharField(default=None, max_length=128, null=True)),
                ('locationnum', models.CharField(default=None, max_length=128, null=True)),
                ('zonecode', models.CharField(default=None, max_length=128, null=True)),
                ('accountcode', models.CharField(default=None, max_length=128, null=True)),
                ('calledportedflag', models.BigIntegerField(default=-1)),
                ('calledimei', models.BigIntegerField(default=-1)),
                ('drccallid', models.CharField(default=None, max_length=128, null=True)),
                ('callredirectionflag', models.BigIntegerField(default=-1)),
                ('globalcallreference', models.CharField(default=None, max_length=128, null=True)),
                ('callerportedflag', models.BigIntegerField(default=-1)),
                ('connectednumber', models.CharField(default=None, max_length=128, null=True)),
                ('smsuserdatatype', models.CharField(default=None, max_length=128, null=True)),
                ('smstext', models.CharField(default=None, max_length=128, null=True)),
                ('maxsmsconcated', models.BigIntegerField(default=-1)),
                ('concatsmsrefnumber', models.BigIntegerField(default=-1)),
                ('seqnoofcurrentsms', models.BigIntegerField(default=-1)),
                ('locationestimate', models.BigIntegerField(default=-1)),
                ('locationupdatetype', models.BigIntegerField(default=-1)),
                ('imeistatus', models.BigIntegerField(default=-1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Job')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='api.Department'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
