# Generated by Django 3.0.7 on 2020-06-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='eventEndDate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='eventStartDate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
