# Generated by Django 3.0.7 on 2020-08-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='lat2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='lng2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
