# Generated by Django 3.0.7 on 2020-07-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('FINISHED', 'FINISHED')], default='PENDING', max_length=32),
        ),
    ]
