# Generated by Django 3.0.7 on 2020-08-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='handsetHistoryJobId',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
