# Generated by Django 3.0.7 on 2020-07-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200724_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='Head',
        ),
    ]
