# Generated by Django 3.0.7 on 2020-08-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200810_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='handsetHistoryStatus',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('FINISHED', 'FINISHED')], default='PENDING', max_length=32),
        ),
    ]
