# Generated by Django 3.0.7 on 2020-07-01 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='analyst',
        ),
        migrations.RemoveField(
            model_name='team',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='case',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='supervisors',
            field=models.ManyToManyField(blank=True, related_name='supervisors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='analysts',
            field=models.ManyToManyField(blank=True, related_name='analysts', to=settings.AUTH_USER_MODEL),
        ),
    ]
