# Generated by Django 3.0.7 on 2020-07-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200701_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='teams', to='api.Team'),
        ),
    ]
