# Generated by Django 3.0.7 on 2020-07-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_calldetailrecord_timebucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldetailrecord',
            name='callerportedflag',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='calledportedflag',
            field=models.BigIntegerField(default=-1),
        ),
    ]
