# Generated by Django 3.0.7 on 2020-08-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200810_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handsethistory',
            name='endTime',
            field=models.BigIntegerField(db_column='endtime', default=-1),
        ),
        migrations.AlterField(
            model_name='handsethistory',
            name='startTime',
            field=models.BigIntegerField(db_column='starttime', default=-1),
        ),
    ]
