# Generated by Django 3.0.7 on 2020-07-01 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20200701_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='teams',
        ),
        migrations.AddField(
            model_name='case',
            name='analysts',
            field=models.ManyToManyField(blank=True, related_name='analysts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='supervisors',
            field=models.ManyToManyField(blank=True, related_name='supervisors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
