# Generated by Django 3.0.7 on 2020-08-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200810_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handsethistory',
            name='history_type',
            field=models.CharField(choices=[('imsi', 'imsi'), ('imei', 'imei'), ('msisdn', 'msisdn')], db_column='type', default=None, max_length=32, null=True),
        ),
    ]
