# Generated by Django 3.0.7 on 2020-07-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200725_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetailrecord',
            name='yyyymm',
            field=models.BigIntegerField(default=-1, null=True),
        ),
    ]
