# Generated by Django 3.0.7 on 2020-07-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200725_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetailrecord',
            name='callreference',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
