# Generated by Django 3.0.7 on 2020-07-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200725_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetailrecord',
            name='accountcode',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='answertime',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='callduration',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='calledimei',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='calledimsi',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='callednumber',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='callingnumber',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='callredirectionflag',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='causeforterm',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='chargedparty',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='chargelevel',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='concatsmsrefnumber',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='connectednumber',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='diagnostics',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='drccallid',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='firstmccmnc',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='globalcallreference',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='imeistatus',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='intermediatemccmnc',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='lastmccmnc',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='locationestimate',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='locationlat',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='locationlon',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='locationnum',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='locationupdatetype',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='maxsmsconcated',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='mscaddress',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='networkcallreference',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='partyrelcause',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='recordingentity',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='recordnumber',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='releasetime',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='seizureordeliverytime',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='seqnoofcurrentsms',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='sequencenumber',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='servedimei',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='servedimsi',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='servedmsisdn',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='smstext',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='smsuserdatatype',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='subscribercategory',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='systemtype',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='timestamp',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='usertype',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='calldetailrecord',
            name='zonecode',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='zone',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
