# Generated by Django 3.0.7 on 2020-07-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200720_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calldetailrecord',
            old_name='calledIMEI',
            new_name='calledimei',
        ),
        migrations.RenameField(
            model_name='calldetailrecord',
            old_name='calledIMSI',
            new_name='calledimsi',
        ),
        migrations.RenameField(
            model_name='calldetailrecord',
            old_name='calledNumber',
            new_name='callednumber',
        ),
        migrations.RenameField(
            model_name='calldetailrecord',
            old_name='calledPortedFlag',
            new_name='calledportedflag',
        ),
        migrations.RenameField(
            model_name='calldetailrecord',
            old_name='callingNumber',
            new_name='callingnumber',
        ),
        migrations.RenameField(
            model_name='calldetailrecord',
            old_name='chargedParty',
            new_name='chargedparty',
        ),
        migrations.RenameField(
            model_name='calldetailrecord',
            old_name='recordingEntity',
            new_name='recordingentity',
        ),
        migrations.AddField(
            model_name='calldetailrecord',
            name='geohash',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
