# Generated by Django 3.0.7 on 2020-07-26 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200725_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='api.Department'),
        ),
        migrations.AlterField(
            model_name='account',
            name='designation',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Supervisor', 'Supervisor'), ('Analyst', 'Analyst')], default='Analyst', max_length=32),
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('Robbery', 'Robbery'), ('Theft', 'Theft'), ('Bomb Blast', 'Bomb Blast'), ('Other', 'Other')], default='Other', max_length=32),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Close', 'Close'), ('Delayed', 'Delayed')], default='Open', max_length=32),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('IMSI', 'IMSI'), ('IMEI', 'IMEI'), ('MSISDN', 'MSISDN'), ('Cell Site', 'Cell Site')], default='IMSI', max_length=32),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('FINISHED', 'FINISHED')], default='Pending', max_length=32),
        ),
    ]
