# Generated by Django 3.0.7 on 2020-07-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200720_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldetailrecord',
            name='yyyymm',
            field=models.IntegerField(default=-1),
        ),
    ]
