# Generated by Django 3.0.7 on 2020-08-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200811_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='city',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='lga',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='state',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
