# Generated by Django 3.0.7 on 2020-07-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200726_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('IMSI', 'IMSI'), ('IMEI', 'IMEI'), ('MSISDN', 'MSISDN'), ('Location', 'Location'), ('LAC/Cell-ID', 'LAC/Cell-ID')], default='IMSI', max_length=32),
        ),
    ]
