# Generated by Django 3.0.7 on 2020-08-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200811_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='zone',
        ),
    ]
