# Generated by Django 3.0.7 on 2020-08-11 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_case_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Case'),
        ),
    ]
