# Generated by Django 3.0.7 on 2020-08-11 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_zone_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=128, null=True)),
                ('description', models.CharField(default=None, max_length=512, null=True)),
                ('address', models.CharField(default=None, max_length=256, null=True)),
                ('city', models.CharField(default=None, max_length=512, null=True)),
                ('zipcode', models.BigIntegerField(default=-1)),
                ('lat', models.BigIntegerField(default=-1)),
                ('lng', models.BigIntegerField(default=-1)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Case')),
            ],
        ),
    ]
