# Generated by Django 3.0.7 on 2020-08-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_poi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='lat',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='poi',
            name='lng',
            field=models.FloatField(default=-1),
        ),
    ]
