# Generated by Django 3.0.7 on 2020-08-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200811_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='lat2',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='lng2',
        ),
        migrations.AlterField(
            model_name='zone',
            name='lat1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='zone',
            name='lng1',
            field=models.CharField(max_length=100),
        ),
    ]
